# Generated by Django 4.2.6 on 2023-12-07 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0003_academico_curso'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Academico_curso',
        ),
        migrations.AddField(
            model_name='curso',
            name='actividad',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
